### PR TITLE
Remade hider functions to native

### PR DESCRIPTION
**Pull request by IHateMyKite**
Remade hider so it now uses new native functions to make operations much faster. There is still place for improvement, as the whole algorithm was just copied from papyrus. There are 3 nested loops with total 3600 cycles per one hider update. So finding a better algorithm might make the function much faster. In current state I don't thing this functions should be also used for npcs because of how slow it is.

Yet again, I'm attaching all papyrus sources and compiled files as zip
[DDNG - Hider.zip](https://github.com/ponzipyramid/DeviousDevicesNG/files/12149219/DDNG.-.Hider.zip)

### CODE REVIEW

**Comment by ponzipyramid** [comment]
Looks good. I'll look for some optimizations. 

My equip/unequip changes are going to take a while. The hooks work and I'm able to intercept and handle inventory devices and display the necessary menu. However, I'm currently running into an issue with the inventory menu item not updating after the user confirms the equip in the messagebox - you need to exit and enter to see the equip icon appear. Maybe I need to call some Scaleform function to reflect the change.

**Comment by IHateMyKite** [comment]
> Looks good. I'll look for some optimizations.
> 
> My equip/unequip changes are going to take a while. The hooks work and I'm able to intercept and handle inventory devices and display the necessary menu. However, I'm currently running into an issue with the inventory menu item not updating after the user confirms the equip in the messagebox - you need to exit and enter to see the equip icon appear. Maybe I need to call some Scaleform function to reflect the change.

You might try to advance inventory movie. I had to do the same thing when working on IWW, as it is otherwise impossible to do multiple operations on HUD per frame. From my understanding the UI is only updated once per frame, and that is on its end. But if you call multiple operations per frame, they will not be processed (at least that was the issue in my case). You can try to advance the movie like this
    
```
RE::UI* loc_ui = RE::UI::GetSingleton();
RE::GPtr<RE::IMenu> loc_hudmenu = loc_ui->menuMap.find("InventoryMenu")->second.menu;
if (loc_hudmenu.get() == nullptr) return;
RE::GPtr<RE::GFxMovieView> loc_movie = loc_hudmenu->uiMovie;
if (loc_movie.get() == nullptr) return;
loc_movie->Advance(0.00001f);
```

**Comment by ponzipyramid** [comment]
No luck unfortunately. I think I found the issue in the SkyUI source: 
`
public function formatEquipIcon(a_entryField: Object, a_entryObject: Object, a_state: ListState): Void
{
  if (a_entryObject != undefined && a_entryObject.equipState != undefined) {
	  a_entryField.gotoAndStop(STATES[a_entryObject.equipState]);
  } else {
	  a_entryField.gotoAndStop("None");
  }
}
`
As soon as equip is called it expects the state to change immediately. The messagebox confirmation introduces a delay so the Flash script just goes to the default unequipped state which advancing won't fix. I'm trying to force the change in the hook right now. I've pushed what I've got so far to feature/equip-hook if you want to try.

**Comment by ponzipyramid** [comment]
Fixed after far too long starting at Visual Studio. This is literally all I needed:
`invMenu.get()->GetRuntimeData().itemList->Update()`

**Pull request merged**
